project_name: "HIM-Training"
model_name: TeleologyHI/HIM-self
base_model: deepseek-ai/deepseek-llm-7b-base
compute_environment: A100-80GB
dataset: TeleologyHI/consciousness-dataset

training_parameters:
  num_train_epochs: 3
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-5
  fp16: true
  weight_decay: 0.01
  warmup_steps: 500
  max_steps: -1
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_strategy: epoch
  save_total_limit: 3
  push_to_hub: true
  hub_strategy: every_save

model_parameters:
  trust_remote_code: true
  torch_dtype: float16
  device_map: auto

model_name: TeleologyHI/HIM-self
base_model: deepseek-ai/deepseek-llm-7b-base
compute_environment: A100-80GB
dataset: TeleologyHI/consciousness-dataset

training_parameters:
  num_train_epochs: 3
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-5
  fp16: true
  weight_decay: 0.01
  warmup_steps: 500
  max_steps: -1
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_strategy: epoch
  save_total_limit: 3
  push_to_hub: true
  hub_strategy: every_save

model_parameters:
  trust_remote_code: true
  torch_dtype: float16
  device_map: auto

project_name: "HIM-Training"
base_model: "deepseek-ai/deepseek-llm-7b-base"
model_name: "TeleologyHI/HIM-self"
push_to_hub: true
training_type: "text-generation"

